from __future__ import annotations


STAGE_REGISTRY = (
    ("VERIFY_FROZEN_BINDINGS", 0),
    ("RUNTIME_MODEL_BINDING", 1),
    ("INPUT_SCENARIO_QUALIFICATION", 2),
    ("DATA_QUALITY_SOURCE_AUTHORITY", 3),
    ("FEATURE_DRIFT", 4),
    ("PREDICTION", 5),
    ("OUTCOME_MATURITY_GATE", 6),
    ("PERFORMANCE_CALIBRATION", 7),
    ("SEGMENT_MONITORING", 8),
    ("ALERT_HEALTH_AGGREGATION", 9),
    ("HISTORY_PERSISTENCE", 10),
    ("MONITORING_REPORT", 11),
    ("DASHBOARD_READINESS", 12),
    ("COMPLETION_EVIDENCE", 13),
)
