"""Stable machine exit codes defined by FINAL-PROJECT-RELEASE-CONTRACT-01."""

from enum import IntEnum


class ExitCode(IntEnum):
    SUCCESS = 0
    CONFIGURATION_OR_CONTRACT_FAILURE = 10
    FROZEN_SOURCE_VERIFICATION_FAILURE = 20
    MANIFEST_CHAIN_FAILURE = 21
    IMMUTABLE_EVIDENCE_DIGEST_FAILURE = 22
    ACTIVE_LOCK = 30
    INVALID_OR_STALE_LOCK = 31
    FROZEN_WRITE_ATTEMPT = 40
    ORCHESTRATION_FAILURE = 50
    REPORT_OR_QUERY_FAILURE = 60
    DEPENDENCY_OR_ENVIRONMENT_FAILURE = 70
    RECEIPT_OR_LOGGING_FAILURE = 80
    UNEXPECTED_FAILURE = 99
